project-name: Quill
base-path: /
assets:
    source: assets
    dest: static
context:
  static:
    site-title: Quill
  dynamic:
    components: session.query(Element).filter(Element.type == "component").all()
    foundations: session.query(Element).filter(Element.type == "foundation").all()