project-name: Quill
base-path: /
assets:
    source: assets
    dest: static
context:
  static:
    site-title: Quill
  dynamic:
    all-authors: session.query(Author).all()
    elements: session.query(Element).filter(Element.published != None).order_by(Element.published.desc()).all()