project-name: Quill
base-path: /
assets:
    source: assets
    dest: static
context:
  static:
    site-title: Quill
    version: 0.9
  dynamic:
    components: session.query(Element).filter(Element.type == "component").filter(Element.published != None).order_by(Element.title).all()
    foundations: session.query(Element).filter(Element.type == "foundation").filter(Element.published != None).order_by(Element.title).all()