project-name: Quill
base-path: /
assets:
    source: assets
    dest: static
context:
  static:
    site-title: Quill
  dynamic:
    all-authors: session.query(Author).all()
    components: session.query(Component).filter(Component.published != None).order_by(Component.published.desc()).all()